### PR TITLE
Retryable options

### PR DESCRIPTION
**Pull request by wlandau**
# Prework

* [x] I understand and agree to the [Contributor Code of Conduct](https://github.com/wlandau/crew.cluster/blob/main/CODE_OF_CONDUCT.md).
* [x] I have already submitted a [discussion topic](https://github.com/wlandau/crew.cluster/discussions) or [issue](https://github.com/wlandau/crew.cluster/issues) to discuss my idea with the maintainer.

# Related GitHub issues and pull requests

* Ref: #48

# Summary

This PR implements retryable options for all `crew.cluster` plugins. Certain arguments of `crew_options_slurm()` etc. can now be vectors, where each successive element applies to the next worker retry and the last element is used if the number of retries exceeds the length of the vector. You can control the number of allowable retries with the `crashes_error` argument of the controller.

Example with SGE and the `sge_memory_gigabytes_required` field:

```r
controller <- crew_controller_sge(
  workers = 16,
  # Try 16 GB memory first, then use 32 GB to retry if the worker crashes,
  # then 64 GB for all subsequent retries:
  sge_memory_gigabytes_required = c(16, 32, 64)
)
```

Memory, CPU, GPU, wall time, and SLURM partition are all retryable now.

### CODE REVIEW

**Comment by wlandau** [comment]
My comment in the code above was not entirely correct. When a worker succeeds (completes all its tasks) and exits normally, the next launch will reset to 16 GB of memory. @stemangiola, do you think this is reasonable? An alternative is to stay at the last memory level that worked, but it may be more resources than necessary, and ultimately I think users could request more memory from the start if there are excessive retries.

**Comment by stemangiola** [comment]
Resetting it is reasonable. If I take my case, I have many small inputs, and some big, and it is hard to partition them properly. 

So I would hope that if `inputBIG` goes to worker `A`, it fails; it gets launched to worker `A` _immediately_ (with priority) with increased resources; when it succeeds, everything can reset expecting small inputs.

**Comment by wlandau** [comment]
Thanks, that helps. And yes, stopped workers with unresolved tasks get launched immediately on the next call to `launcher$scale()`. In the code, the are called "backlogged workers": https://github.com/wlandau/crew/blob/da957aea7a58f147b9c9d424148b166a830e2d5e/R/crew_launcher.R#L874-L875

**Comment by stemangiola** [comment]
Thinking about it, form a user perspective, it would be nice to have the next-try visible to the user. For example something like 

"Submitted batch job 19176672 - retried with these resources ..."

**Comment by wlandau** [comment]
The latest few commits add a brief retry message (without specific resources because those are case-by-case and potentially long)

**Comment by wlandau** [comment]
As of version 2.0.0, `mirai` is moving away from the retry policy that made retryable options possible in the `crew` ecosystem. As part of https://github.com/wlandau/crew/issues/193, I will need to find another way for `crew` to increase resources when it retries tasks. I think a tiering system based on controller groups is the most appropriate. I'm picturing something like what you had in [HPCell](https://github.com/MangiolaLaboratory/HPCell) except that a crashed task would automatically iterate to over different controllers in the group as needed.

**Comment by stemangiola** [comment]
I have to say retractable options (with elastic resources) saved me so many hours of restarting the pipelines; it is a game change for large-scale real-world pipelines.

One resource with an array of parameters is very convenient and powerful, I guess a tiering system is a bit more cumbersome but would still work.

**Comment by stemangiola** [comment]
FYI @myushen

**Pull request merged**
